#!/bin/bash

RELEASE="__CURRENT_RELEASE__"
RELEASE_BASE_URL="https://github.com/billisonline/vphp/releases/download/${RELEASE}"

VPHP_FILENAME="vphp"
VPHP_PATH="./${VPHP_FILENAME}"
VPHP_URL="${RELEASE_BASE_URL}/${VPHP_FILENAME}"

rm -f "$VPHP_PATH"

curl -sL "$VPHP_URL" > "$VPHP_PATH"

chmod +x "$VPHP_PATH"

"$VPHP_PATH" m:init
