#!/bin/bash

RELEASE="__CURRENT_RELEASE__"
RELEASE_BASE_URL="https://github.com/billisonline/lphp/releases/download/${RELEASE}"

LPHP_FILENAME="lphp"
LPHP_PATH="./${LPHP_FILENAME}"
LPHP_URL="${RELEASE_BASE_URL}/${LPHP_FILENAME}"

rm -f "$LPHP_PATH"

curl -sL "$LPHP_URL" > "$LPHP_PATH"

chmod +x "$LPHP_PATH"

"$LPHP_PATH" m:init
