name: Multi-OS Build Test

env:
  CACHE_KEY_PHP_SOURCES: spc-2.5.2-php-8.4-sources
  CACHE_KEY_PHP_BUILDS: spc-2.5.2-php-8.4-builds

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache PHP sources
        id: cache-php-sources
        uses: actions/cache@v4
        with:
          path: ./build/downloads.zip
          key: ${{ env.CACHE_KEY_PHP_SOURCES }}

      - if: ${{ steps.cache-php-sources.outputs.cache-hit != 'true' }}
        name: Download PHP and extension sources
        run: ./ci/download-sources.sh

  build:
    strategy:
      matrix:
        config:
          - os_type: macos
            os_display_name: macOS
            runner: macos-latest
          - os_type: linux
            os_display_name: Linux (glibc)
            runner: ubuntu-latest

    needs: download

    runs-on: ${{ matrix.config.runner }}
    permissions:
      contents: read
    outputs:
      php_artifact_name: php-${{ matrix.config.os_type }}.zip

    steps:
      - uses: actions/checkout@v4

      - name: Download cached PHP sources
        uses: actions/cache@v4
        with:
          path: ./build/downloads.zip
          key: ${{ env.CACHE_KEY_PHP_SOURCES }}

      - name: Cache PHP build
        id: cache-php-build
        uses: actions/cache@v4
        with:
          path: ./build/output/php-${{ matrix.config.os_type }}.zip
          key: ${{ env.CACHE_KEY_PHP_BUILDS }}-${{ matrix.config.os_type }}

      - if: ${{ steps.cache-php-build.outputs.cache-hit != 'true' }}
        name: Build PHP for ${{ matrix.config.os_display_name }}
        run: ./ci/build-php-${{ matrix.config.os_type }}.sh

      - name: Archive PHP build for ${{ matrix.config.os_display_name }}
        uses: actions/upload-artifact@v4
        with:
          name: php-${{ matrix.config.os_type }}
          path: ./build/output/php-${{ matrix.config.os_type }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RELEASE: '0.04'
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Delete release if it already exists
        run: |
          gh release list --json tagName -q '.[] | .tagName' | grep -xqF ${{ env.RELEASE }} \
            && gh release delete ${{ env.RELEASE }} \
            || echo "No existing release ${{ env.RELEASE }}"

      - name: Create release
        run: gh release create ${{ env.RELEASE }}

      - name: Download all PHP build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./build/artifacts

      - name: Upload all PHP builds to release
        run: |
          gh release upload ${{ env.RELEASE }} ./build/artifacts/**/php-*.zip

      - name: Generate installer patch template
        run: ./ci/generate-installer-patch.sh > ./templates/install-phpw.patch

      - name: Build PHPW runner, installer, and patch from templates
        run: |
          mkdir -p ./build/output
          sed "s|__CURRENT_RELEASE__|$RELEASE|g" ./templates/phpw > ./build/output/phpw
          sed "s|__CURRENT_RELEASE__|$RELEASE|g" ./templates/install-phpw > ./build/output/install-phpw
          sed "s|__CURRENT_RELEASE__|$RELEASE|g" ./templates/install-phpw.patch > ./build/output/install-phpw.patch

      - name: Add PHPW, installer script, and installer patch to release
        run: |
          gh release upload ${{ env.RELEASE }} \
            ./build/output/phpw \
            ./build/output/install-phpw \
            ./build/output/install-phpw.patch
