name: MacOS build test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      RELEASE: '0.03'
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Create release
        run: gh release create ${{ env.RELEASE }}

      - name: Build PHP for macOS
        run: ./ci/build-php.sh
      
      - name: Add PHP for macOS to release
        run: gh release upload ${{ env.RELEASE }} ./build/output/php-macos.zip

      - name: Build LPHP and installer scripts from template
        run: |
          sed "s|__CURRENT_RELEASE__|$RELEASE|g" ./templates/lphp > ./build/output/lphp
          sed "s|__CURRENT_RELEASE__|$RELEASE|g" ./templates/lphp-installer > ./build/output/lphp-installer

      - name: Add LPHP and installer scripts to release
        run: gh release upload ${{ env.RELEASE }} ./build/output/lphp ./build/output/lphp-installer
