name: MacOS build test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build PHP
        run: ./build.sh
      
      - name: Create release
        run: gh release --repo ${{ github.repository }} create 0.01 ./build/output/php-macos
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
